# Generated by Django 6.0.4 on 2026-04-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('ORANGE', 'Orange CM'), ('MTN', 'MTN CM'), ('CAMTEL', 'Camtel'), ('NEXTTEL', 'Nexttel'), ('YOOMEE', 'Yoomee')], max_length=10, verbose_name='Operateur')),
                ('ville', models.CharField(choices=[('YAOUNDE', 'Yaounde'), ('DOUALA', 'Douala'), ('BAFOUSSAM', 'Bafoussam'), ('BAMENDA', 'Bamenda'), ('GAROUA', 'Garoua'), ('MAROUA', 'Maroua'), ('NGAOUNDERE', 'Ngaoundere'), ('BERTOUA', 'Bertoua'), ('EBOLOWA', 'Ebolowa'), ('BUEA', 'Buea'), ('LIMBE', 'Limbe'), ('KRIBI', 'Kribi'), ('EDEA', 'Edea'), ('NKONGSAMBA', 'Nkongsamba'), ('FOURAMBAN', 'Fourabam'), ('AUTRE', 'Autre ville')], max_length=20, verbose_name='Ville')),
                ('quartier', models.CharField(help_text='Ex: Bastos, Bonanjo, Obili...', max_length=100, verbose_name='Quartier')),
                ('type_reseau', models.CharField(choices=[('2G', '2G (Edge)'), ('3G', '3G (H+)'), ('4G', '4G / LTE'), ('5G', '5G'), ('FIBRE', 'Fibre optique'), ('WIFI', 'Wi-Fi')], max_length=10, verbose_name='Type de reseau')),
                ('qualite_appel', models.IntegerField(help_text='1 = Coupures frequentes, 5 = Impeccable', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualite des appels')),
                ('debit_internet', models.IntegerField(help_text='1 = Tres lent, 5 = Tres rapide', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Debit internet')),
                ('stabilite', models.IntegerField(help_text='1 = Deconnexions frequentes, 5 = Tres stable', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stabilite')),
                ('couverture', models.IntegerField(help_text='1 = Pas de reseau, 5 = Pleine barre', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Couverture')),
                ('moment_journee', models.CharField(choices=[('MATIN', 'Matin (6h-12h)'), ('APRES_MIDI', 'Apres-midi (12h-18h)'), ('SOIR', 'Soir (18h-22h)'), ('NUIT', 'Nuit (22h-6h)')], default='APRES_MIDI', max_length=15, verbose_name='Moment de la journee')),
                ('meteo', models.CharField(choices=[('SEC', 'Temps sec'), ('PLUIE', 'Pluie legere'), ('ORAGE', 'Orage / Forte pluie'), ('VENT', 'Vent fort / Harmattan'), ('NUAGEUX', 'Nuageux')], default='SEC', max_length=10, verbose_name='Meteo')),
                ('forfait_prix', models.IntegerField(blank=True, help_text='Optionnel : pour analyse qualite/prix', null=True, verbose_name='Prix du forfait (FCFA)')),
                ('commentaire', models.TextField(blank=True, help_text='Decrivez votre experience (500 caracteres max)', max_length=500, null=True, verbose_name='Commentaire')),
                ('score_composite', models.FloatField(editable=False, null=True, verbose_name='Score IQR')),
                ('categorie_zone', models.CharField(editable=False, max_length=30, null=True, verbose_name='Categorie de zone')),
                ('ip_address', models.GenericIPAddressField(editable=False, null=True, verbose_name='Adresse IP')),
                ('identifiant_unique', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Identifiant unique')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement')),
            ],
            options={
                'verbose_name': 'Signalement reseau',
                'verbose_name_plural': 'Signalements reseau',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
