# Generated by Django 6.0.4 on 2026-04-28 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementreseau',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AddField(
            model_name='signalementreseau',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='couverture',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Couverture'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='debit_internet',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Debit internet'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='forfait_prix',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix du forfait (FCFA)'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='qualite_appel',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualite des appels'),
        ),
        migrations.AlterField(
            model_name='signalementreseau',
            name='stabilite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stabilite'),
        ),
    ]
