# Generated by Django 6.0.4 on 2026-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0002_signalementreseau_dislikes_signalementreseau_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementreseau',
            name='modele_telephone',
            field=models.CharField(blank=True, help_text='Optionnel : Ex: Samsung A14, iPhone 12...', max_length=100, null=True, verbose_name='Modèle du téléphone'),
        ),
        migrations.AddField(
            model_name='signalementreseau',
            name='puissance_signal',
            field=models.CharField(blank=True, help_text='Optionnel : RSSI, RSRP, RSRQ', max_length=10, null=True, verbose_name='Puissance du signal'),
        ),
    ]
